"""empty message

Revision ID: 4c46f3be5e6a
Revises: a116fc36ddaf
Create Date: 2017-07-15 21:14:22.978969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c46f3be5e6a'
down_revision = 'a116fc36ddaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_body_html', sa.Text(), nullable=False))
    op.drop_column('posts', 'post_body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_body', mysql.TEXT(), nullable=False))
    op.drop_column('posts', 'post_body_html')
    # ### end Alembic commands ###
