"""empty message

Revision ID: a116fc36ddaf
Revises: 20f17b9d8261
Create Date: 2017-07-15 20:53:23.817372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a116fc36ddaf'
down_revision = '20f17b9d8261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_body_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_body_text')
    # ### end Alembic commands ###
